from .chatbot_create_api_view import ChatbotCreateAPIView
from .chatbot_list_update_api_view import ChatbotListUpdateAPIView
from .feedback_create_api_view import FeedbackCreateAPIView
from .feedback_comment_create_api_view import FeedbackCommentCreateAPIView
from .chatbot_check_api_view import ChatbotCheckAPIView
