# Generated by Django 3.2 on 2023-06-24 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chatbot',
            old_name='text',
            new_name='content',
        ),
        migrations.RenameField(
            model_name='chatbot',
            old_name='user',
            new_name='session_id',
        ),
        migrations.RemoveField(
            model_name='chatbot',
            name='data',
        ),
        migrations.AddField(
            model_name='chatbot',
            name='reference',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='chatbot',
            name='type',
            field=models.BooleanField(default=False),
            preserve_default=False,
        ),
    ]
