# Generated by Django 3.2 on 2023-06-24 01:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0002_auto_20230624_1031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='content',
            field=models.TextField(default=False),
        ),
    ]
