# Generated by Django 3.2 on 2023-06-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_alter_chatbot_content'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chatbot',
            name='content',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='chatbot',
            name='type',
            field=models.BooleanField(default=False),
        ),
    ]
